export const animations = [
  {
    label: 'Attention',
    children: [
      { label: 'Bounce', value: 'bounce' },
      { label: 'Flash', value: 'flash' },
      { label: 'Pulse', value: 'pulse' },
      { label: 'Rubber Band', value: 'rubberBand' },
      { label: 'Head Shake', value: 'headShake' },
      { label: 'Swing', value: 'swing' },
      { label: 'Tada', value: 'tada' },
      { label: 'Wobble', value: 'wobble' },
      { label: 'Jello', value: 'jello' },
    ]
  },
  {
    label: 'Entrance',
    children: [
      { label: 'Fade In', value: 'fadeIn' },
      { label: 'Fade In Left', value: 'fadeInLeft' },
      { label: 'Fade In Right', value: 'fadeInRight' },
      { label: 'Fade In Up', value: 'fadeInUp' },
      { label: 'Fade In Down', value: 'fadeInDown' },
      { label: 'Fade In Left Big', value: 'fadeInLeftBig' },
      { label: 'Fade In Right Big', value: 'fadeInRightBig' },
      { label: 'Fade In Up Big', value: 'fadeInUpBig' },
      { label: 'Fade In Down Big', value: 'fadeInDownBig' },
      { label: 'Rotate In', value: 'rotateIn' },
      { label: 'Rotate In Down Left', value: 'rotateInDownLeft' },
      { label: 'Rotate In Down Right', value: 'rotateInDownRight' },
      { label: 'Rotate In Up Left', value: 'rotateInUpLeft' },
      { label: 'Rotate In Up Right', value: 'rotateInUpRight' },
      { label: 'Bounce In', value: 'bounceIn' },
      { label: 'Bounce In Left', value: 'bounceInLeft' },
      { label: 'Bounce In Right', value: 'bounceInRight' },
      { label: 'Bounce In Up', value: 'bounceInUp' },
      { label: 'Bounce In Down', value: 'bounceInDown' },
      { label: 'Light Speed In Right', value: 'lightSpeedInRight' },
      { label: 'Light Speed In Left', value: 'lightSpeedInLeft' },
      { label: 'Light Speed Out Right', value: 'lightSpeedOutRight' },
      { label: 'Light Speed Out Left', value: 'lightSpeedOutLeft' },
      { label: 'Flip', value: 'flip' },
      { label: 'Flip In X', value: 'flipInX' },
      { label: 'Flip In Y', value: 'flipInY' },
      { label: 'Roll In', value: 'rollIn' },
      { label: 'Zoom In', value: 'zoomIn' },
      { label: 'Zoom In Left', value: 'zoomInLeft' },
      { label: 'Zoom In Right', value: 'zoomInRight' },
      { label: 'Zoom In Up', value: 'zoomInUp' },
      { label: 'Zoom In Down', value: 'zoomInDown' },
      { label: 'Slide In Left', value: 'slideInLeft' },
      { label: 'Slide In Right', value: 'slideInRight' },
      { label: 'Slide In Up', value: 'slideInUp' },
      { label: 'Slide In Down', value: 'slideInDown' }
    ]
  }
]
