import { IconConfig } from '../Default/Icon/index'
import { PackagesCategoryEnum } from '@/packages/index.d'
import { ChatCategoryEnum, ChatCategoryEnumName } from '../index.d'

const iconNames = [
  // Server
  'mdi:server',
  'mdi:server-outline',
  'mdi:server-network',
  'mdi:server-network-off',
  'mdi:server-plus',
  'mdi:server-off',
  'mdi:server-security',
  'mdi:desktop-tower',
  'mdi:nas',
  'mdi:harddisk',
  'mdi:memory',
  'mdi:chip',
  'mdi:cpu-64-bit',
  'mdi:database',
  'mdi:database-outline',
  'mdi:database-cog',
  'mdi:database-lock',
  'mdi:console',
  'mdi:console-line',
  'mdi:console-network',
  'mdi:docker',
  'mdi:kubernetes',
  // Network
  'mdi:lan',
  'mdi:lan-connect',
  'mdi:lan-disconnect',
  'mdi:lan-pending',
  'mdi:network',
  'mdi:ip-network',
  'mdi:router',
  'mdi:router-network',
  'mdi:switch',
  'mdi:hub',
  'mdi:ethernet',
  'mdi:ethernet-cable',
  'mdi:cable-data',
  'mdi:wifi',
  'mdi:wifi-strength-4',
  'mdi:access-point',
  'mdi:access-point-network',
  'mdi:antenna',
  'mdi:satellite-uplink',
  'mdi:dns',
  'mdi:vpn',
  'mdi:security-network',
  'mdi:shield-lock',
  'mdi:shield-check',
  'mdi:sitemap',
  'mdi:folder-network',
  'mdi:swap-horizontal',
  'mdi:api',
  // Cloud
  'mdi:cloud',
  'mdi:cloud-outline',
  'mdi:cloud-upload',
  'mdi:cloud-download',
  'mdi:cloud-sync',
  'mdi:cloud-check',
  'mdi:cloud-alert',
  'mdi:cloud-lock',
  'mdi:cloud-braces',
  'mdi:aws',
  'mdi:microsoft-azure',
  'mdi:google-cloud',
  'mdi:web',
  'mdi:earth',
  'mdi:monitor-dashboard',
  'mdi:code-braces'
]
const iconList = iconNames.map(name => ({
  ...IconConfig,
  category: ChatCategoryEnum.IT,
  categoryName: ChatCategoryEnumName.IT,
  package: PackagesCategoryEnum.ICONS,
  image: name,
  icon: name,
  dataset: name,
  title: name.replace('mdi:', ''),
  redirectComponent: `${IconConfig.package}/${IconConfig.category}/${IconConfig.key}`
}))

export default iconList
